# fly.toml app configuration file for bot-wa-nameless-shadow-952
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-wa-nameless-shadow-952'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # Cambiado de 'stop' a false
  auto_start_machines = true
  min_machines_running = 1    # Cambiado de 0 a 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1